[package]
name = "rust-ul-next"
version = "0.1.0"
edition = "2021"


[features]
default = []
# link only Ultralight unique libraries, and not other dependancies that
# may be available in the host system (such as libglib and libgio)
only-ul-deps = ["ul-sys/only-ul-deps"]


[dependencies]
ul-sys = { version = "1.3.3-alpha.0", git = "https://github.com/VideowindoW/rust-ul-sys", rev = "aa9ac9cbb4e852cc522b90ee887001e694dca638" }
scopeguard = "1.1.0"
lazy_static = "1.4.0"
glium = { version = "0.31.0", default-features = false, features = [], optional = true }
thiserror = "1.0.31"



[dev-dependencies]
png = "0.17.5"
glium = "0.31.0"

[[example]]
name = "glium_custom_gpu_driver"
required-features = ["glium"]
