[package]
name = "rust-ul-next"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ul-sys = { version = "1.3.3-alpha.0", git = "https://github.com/Amjad50/rust-ul-sys", branch = "master" }
scopeguard = "1.1.0"
lazy_static = "1.4.0"
