pub(crate) const EMPTY_CLASS_DEF: ul_sys::JSClassDefinition = ul_sys::JSClassDefinition {
    version: 0,
    attributes: 0,
    className: std::ptr::null(),
    parentClass: std::ptr::null_mut(),
    staticValues: std::ptr::null(),
    staticFunctions: std::ptr::null(),
    initialize: None,
    finalize: None,
    hasProperty: None,
    getProperty: None,
    setProperty: None,
    deleteProperty: None,
    getPropertyNames: None,
    callAsFunction: None,
    callAsConstructor: None,
    hasInstance: None,
    convertToType: None,
};
